name: Android CICD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop
  jobs:
    test:
      name: Test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '17'
            cache: gradle

        - name: Grant execute permission
          run: chmod +x ./gradlew

        - name: Run unit tests
          run: ./gradle test

        - name: Run lint
          run: ./gradlew lint


    build:
      name: Build debug APK
      needs: test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '17'
            cache: gradle

        - name: Grant execution permission
          run: chmod +x ./gradlew

        - name: Build APK
          run: ./gradlew assembleDebug

        - name: Upload APK
          uses: actions/upload-artifact@v4
          with:
            name: app-debug
            path: app/build/outputs/apk/debug/*.apk


    release:
      name: Build Release AAB
      needs: test
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '17'
            cache: gradle

        - name: Grant execute permission
          run: chmod +x ./gradlew

        - name: Build release bundle
          run: ./gradlew bundleRelease

        - name: Upload AAB
          uses: actions/upload-artifact@v4
          with:
            name: app-release
            path: app/build/outputs/bundle/release/*.aab
